# Generated by Django 3.0 on 2022-05-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
